baseURL = "https://www.olehammersland.com"

title = "Ole Hammersland"
copyright = "Ole Hammersland©2021"
languageCode = "en-US"

enableRobotsTXT = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blogg/:slug"

[params]
  authorName = "Ole Hammersland"
  # Alpine JS CDN
  alpineCDN= "https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"

  description = "Min hjemmeside. Jeg arbeider med oversettelse fra tysk, engelsk, dansk og svensk."

  favicon = "images/favicon.png"

  images = ["images/share.png"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "vim"
    tabWidth = 4
  
  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2
